name: standard_app_dev

services:
  frontend:  # ← base 側のサービス名と一致させる
    build:
      dockerfile: Dockerfile
      target: dev
      args:
        NODE_IMAGE: node:25-trixie
    volumes:
      - ./frontend:/app
    command: >
      sh -lc "if [ ! -x node_modules/.bin/next ]; 
        then if [ -f package-lock.json ]; 
            then npm ci; 
            else npm install; 
          fi; 
        fi; 
      npm run dev"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    networks:
        - internal
        - edge
  api:
    build:
      dockerfile: Dockerfile
      target: dev
      args:
        GOLANG_IMAGE: golang:1.25-bookworm
    volumes:
      - ./api:/app:cached
      - go-mod:/go/pkg/mod   # go mod キャッシュ
      - go-build:/root/.cache/go-build
    networks:
      - internal
      - edge
volumes:
  go-mod:
  go-build:
